server:
  port: 8082
spring:
  application:
    name: order-service
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
  hystrix:
    enabled: true #开启Hystrix熔断器

# 断路器监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
