server:
  port: 8080
spring:
  application:
    name: gateway-zuul
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: user-service
    api-order:
      path: /api-order/**
      serviceId: order-service