server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    register-with-eureka: false  # 不要使用 eureka 服务进行注册
    fetch-registry: false # 不要在本地缓存注册表信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
